### ISSUE TITLE
Should possibly always call `handler`

### ISSUE THREAD

**Issue by avioli** [redstrate/procreate-viewer#4]
Good job on this nice app!

A friendly advice - you should call the `handler` and not just return.

The already available `err` can be used at the top level if-else block:

```swift
} else {
    NSLog("Could not find file \(intent.url.lastPathComponent) to preview it")
    handler(err)
}
```

Then the caught error:

```swift
} catch {
    NSLog("Could not load file \(intent.url.lastPathComponent) to preview it")
    handler(error)
}
```

Then you have to make your own for the three guard blocks:

```swift
let err = NSError(domain: "procreate-viewer", code: 1, userInfo: nil)
handler(err)
```

Current code:

https://github.com/redstrate/procreate-viewer/blob/b469cc3a96e20efd7a8376d80e86cfe029f7eaab/Quicklook/PreviewViewController.swift#L12-L40

Similar notes for the thumbnail handler.

**Comment by redstrate** [comment]
Thank you for your contribution! I added calling to the handler function in all error paths, however instead of calling in each guard block I actually just threw, so it propagates up like this:
```swift
let standardError = NSError(domain: "procreate-viewer", code: 1, userInfo: nil)

do {
    guard let archive = Archive(data: try Data(contentsOf: request.fileURL), accessMode: Archive.AccessMode.read) else {
        throw standardError
    }
    ...
```

**Comment by avioli** [comment]
I believe `NSFileCoordinator.coordinate` will simply call the `byAccessor` block and not capture any thrown errors, thus the `throw` will most probably crash the process that invokes your controller and hopefully the QuickLook process will handle it somehow gracefully. 🤞 (You can test by simply throwing straight away and see what happens)

In your `catch` block you return `err`, which is `nil` at that point. I've noted that you should return `error`, which is a local constant that the catch block explicitly sets (see [Handling Errors Using Do-Catch](https://docs.swift.org/swift-book/LanguageGuide/ErrorHandling.html#ID541)). You can specify a name by using `} catch let someVarName {` and then use that constant.

https://github.com/redstrate/procreate-viewer/blob/9ba67adae4ec907022f997ab2aa0f8e6e1955927/Quicklook/PreviewViewController.swift#L12-L44
